### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ghost** [WetABQ/Nukkit-AntiCheat#2]
17:46:26 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerMoveEvent' to 'AntiCheat v1.1.0': null on top.dreamcity.AntiCheat.Event.Listener.EventListener
17:46:26 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.Player.processMovement(Player.java:1527)
        at cn.nukkit.Player.onUpdate(Player.java:1658)
        at cn.nukkit.level.Level.doTick(Level.java:754)
        at cn.nukkit.Server.checkTickUpdates(Server.java:989)
        at cn.nukkit.Server.tick(Server.java:1075)
        at cn.nukkit.Server.tickProcessor(Server.java:838)
        at cn.nukkit.Server.start(Server.java:815)
        at cn.nukkit.Server.<init>(Server.java:498)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)
Caused by: java.lang.IncompatibleClassChangeError: Found interface cn.nukkit.math.AxisAlignedBB, but class was expected
        at top.dreamcity.AntiCheat.Cheat.move.CheckBB.isCheat(CheckBB.java:42)
        at top.dreamcity.AntiCheat.Event.Listener.EventListener.onMove(EventListener.java:95)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 11 more

**Comment by WetABQ** [comment]
I will not be able to maintain this plugin anymore
But this bug I may go to fix this bug

**Comment by ghost** [comment]
Ok :D

**Comment by WetABQ** [comment]
Fix.Merged a large number of changes. See 8ae2a9dfde58a5fc4daae20185de6aa44952269b
