### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by ghost** [WetABQ/Nukkit-AntiCheat#5]
> java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedEntrySet.forEach(Unknown Source)
        at cn.nukkit.utils.ConfigSection.exists(ConfigSection.java:682))

        at cn.nukkit.Server.isOp(Server.java:1944)
        at cn.nukkit.Player.isOp(Player.java:457)
        at top.dreamcity.AntiCheat.Cheat.move.AntiFlyPlayerThread.onRun(AntiFlyPlayerThread.java:39)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
15:53:27        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

15:53:27 [CRITICAL] Exception in asynchronous task
java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedEntrySet.forEach(Unknown Source)
        at cn.nukkit.utils.ConfigSection.getKeys(ConfigSection.java:724)
        at cn.nukkit.utils.ConfigSection.exists(ConfigSection.java:682)
        at cn.nukkit.utils.Config.exists(Config.java:410)
        at cn.nukkit.Server.isOp(Server.java:1944)
        at cn.nukkit.Player.isOp(Player.java:457)
        at top.dreamcity.AntiCheat.Cheat.move.AntiFlyPlayerThread.onRun(AntiFlyPlayerThread.java:39)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by WetABQ** [comment]
this error is normal, you can not care about it
i will hide that in future.

**Comment by WetABQ** [comment]
fixed in WAC
